### ISSUE TITLE
RocmInfo segfaulting with Vega

### ISSUE THREAD

**Issue by madscientist159** [ROCm/rocminfo#8] opened 2018-11-14 12:46 UTC
Trying to use ROCm 1.9 from the AMD Debian repository with a Vega card on an Opteron (PCIe Gen 2) mainboard.  All GPU applications are causing a segmentation fault including ```rocminfo```:

```
gdb /opt/rocm/bin/rocminfo
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/rocm/bin/rocminfo...(no debugging symbols found)...done.
(gdb) r
Starting program: /opt/rocm/bin/rocminfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b700a0 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libhsa-runtime64.so.1
(gdb)
```

amdgpu and kfd are the correct versions:

```
modinfo amdgpu | grep filename
filename:       /lib/modules/4.15.0/updates/dkms/amdgpu.ko
```

```
modinfo amdkfd | grep filename
filename:       /lib/modules/4.15.0/updates/dkms/amdkfd.ko
```

No loading faults are present:

```
[   19.414214] kfd kfd: Initialized module
[   19.414905] [drm] initializing kernel modesetting (VEGA10 0x1002:0x687F 0x1849:0x1001 0xC3).
[   19.414984] [drm] register mmio base: 0xF8000000
[   19.415037] [drm] register mmio size: 524288
[   19.415100] [drm] probing gen 2 caps for device 1022:1471 = 700d03/e
[   19.415155] [drm] probing mlw for device 1022:1471 = 700d03
[   19.415210] [drm] add ip block number 0 <soc15_common>
[   19.415263] [drm] add ip block number 1 <gmc_v9_0>
[   19.415315] [drm] add ip block number 2 <vega10_ih>
[   19.415368] [drm] add ip block number 3 <psp>
[   19.415420] [drm] add ip block number 4 <powerplay>
[   19.415472] [drm] add ip block number 5 <dm>
[   19.415524] [drm] add ip block number 6 <gfx_v9_0>
[   19.415577] [drm] add ip block number 7 <sdma_v4_0>
[   19.415631] [drm] add ip block number 8 <uvd_v7_0>
[   19.415684] [drm] add ip block number 9 <vce_v4_0>
[   19.422533] [drm] UVD(0) is enabled in VM mode
[   19.422588] [drm] UVD(0) ENC is enabled in VM mode
[   19.422641] [drm] VCE enabled in VM mode
[   19.422739] amdgpu 0000:03:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0x0000
[   19.422840] ATOM BIOS: 113-EXT23640-PRI
[   19.422938] [drm] vm size is 32 GB, 3 levels, block size is 9-bit, fragment size is 9-bit
[   19.423009] amdgpu 0000:03:00.0: VRAM: 8176M 0x000000F400000000 - 0x000000F5FEFFFFFF (8176M used)
[   19.423072] amdgpu 0000:03:00.0: GTT: 512M 0x000000F600000000 - 0x000000F61FFFFFFF
[   19.423143] [drm] Detected VRAM RAM=8176M, BAR=256M
[   19.423198] [drm] RAM width 2048bits HBM
[   19.423509] [TTM] Zone  kernel: Available graphics memory: 3727627 kiB
[   19.423569] [TTM] Initializing pool allocator
[   19.423637] [TTM] Initializing DMA pool allocator
[   19.423748] [drm] amdgpu: 8176M of VRAM memory ready
[   19.423804] [drm] amdgpu: 8176M of GTT memory ready.
[   19.423878] [drm] GART: num cpu pages 131072, num gpu pages 131072
[   19.424060] [drm] PCIE GART of 512M enabled (table at 0x000000F400900000).
[   19.458846] [drm] use_doorbell being set to: [true]
[   19.459017] [drm] use_doorbell being set to: [true]
[   19.465385] [drm] Found UVD firmware Version: 1.50 Family ID: 17
[   19.465465] [drm] PSP loading UVD firmware
[   19.469659] [drm] Found VCE firmware Version: 53.19 Binary ID: 4
[   19.469732] [drm] PSP loading VCE firmware
[   19.619225] [drm] reserve 0x400000 from 0xf400c00000 for PSP TMR SIZE
[   19.619443] firewire_core 0000:0a:02.0: created device fw0: GUID 001e8c0000e54dda, S400
[   19.914160] [drm] Display Core initialized with v3.1.47!
[   19.915007] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   19.915064] [drm] Driver supports precise vblank timestamp query.
[   19.938488] [drm] UVD and UVD ENC initialized successfully.
[   20.038170] [drm] VCE initialized successfully.
[   20.044110] kfd kfd: Allocated 3969056 bytes on gart
[   20.044201] Virtual CRAT table created for GPU
[   20.044257] Parsing CRAT table with 1 nodes
[   20.044337] Creating topology SYSFS entries
[   20.044728] Topology: Add dGPU node [0x687f:0x1002]
[   20.044917] kfd kfd: added device 1002:687f
[   20.045667] [drm] Cannot find any crtc or sizes
[   20.045967] amdgpu 0000:03:00.0: ring 0(gfx) uses VM inv eng 4 on hub 0
[   20.046027] amdgpu 0000:03:00.0: ring 1(comp_1.0.0) uses VM inv eng 5 on hub 0
[   20.046097] amdgpu 0000:03:00.0: ring 2(comp_1.1.0) uses VM inv eng 6 on hub 0
[   20.046165] amdgpu 0000:03:00.0: ring 3(comp_1.2.0) uses VM inv eng 7 on hub 0
[   20.046231] amdgpu 0000:03:00.0: ring 4(comp_1.3.0) uses VM inv eng 8 on hub 0
[   20.046296] amdgpu 0000:03:00.0: ring 5(comp_1.0.1) uses VM inv eng 9 on hub 0
[   20.046359] amdgpu 0000:03:00.0: ring 6(comp_1.1.1) uses VM inv eng 10 on hub 0
[   20.046423] amdgpu 0000:03:00.0: ring 7(comp_1.2.1) uses VM inv eng 11 on hub 0
[   20.046487] amdgpu 0000:03:00.0: ring 8(comp_1.3.1) uses VM inv eng 12 on hub 0
[   20.046551] amdgpu 0000:03:00.0: ring 9(kiq_2.1.0) uses VM inv eng 13 on hub 0
[   20.046618] amdgpu 0000:03:00.0: ring 10(sdma0) uses VM inv eng 4 on hub 1
[   20.046679] amdgpu 0000:03:00.0: ring 11(sdma1) uses VM inv eng 5 on hub 1
[   20.046739] amdgpu 0000:03:00.0: ring 12(uvd<0>) uses VM inv eng 6 on hub 1
[   20.046796] amdgpu 0000:03:00.0: ring 13(uvd_enc0<0>) uses VM inv eng 7 on hub 1
[   20.046860] amdgpu 0000:03:00.0: ring 14(uvd_enc1<0>) uses VM inv eng 8 on hub 1
[   20.046924] amdgpu 0000:03:00.0: ring 15(vce0) uses VM inv eng 9 on hub 1
[   20.046981] amdgpu 0000:03:00.0: ring 16(vce1) uses VM inv eng 10 on hub 1
[   20.047038] amdgpu 0000:03:00.0: ring 17(vce2) uses VM inv eng 11 on hub 1
[   20.047146] [drm] ECC is not present.
[   20.047858] [drm] Initialized amdgpu 3.26.0 20150101 for 0000:03:00.0 on minor 0
```

Strangely ```rocm-smi``` works:

```
/opt/rocm/bin/rocm-smi


====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD    MCLK OD
  0   34c     4.0W     852Mhz   167Mhz   12.94%   auto      0%         0%
================================================================================
====================           End of ROCm SMI Log          ====================
```

**Comment by jlgreathouse** [comment] 2018-11-14 14:53
It's not too strange that `rocm-smi` works. It's a Python script that's reading files out of sysfs rather than directly interacting with the driver.

What distro is this, and what steps did you go through to perform the ROCm installation?

Could you attach an strace output of what happens when you run `rocminfo`?

**Comment by madscientist159** [comment] 2018-11-19 18:03
Do you need any more information to debug?  Been trying to use ROCm off and on for many months now, have never been able to actually get it to work.

**Comment by cfreehill** [comment] 2018-11-19 20:54
Hi,

I'm not sure what the issue is. rocminfo just calls the runtime ROCr to get
information and display it. ROCr gets the information from sysfs, which is
populated by KFD. Usually when there is such a problem it could be that
ROCm (the KFD part in particular) isn't running right or isn't installed
right.

Here are some sysfs files that should have meaningful data:

   - /sys/devices/virtual/kfd/kfd/topology/nodes/ should have integer
   number directories, 1 for each gpu or cpu.
   - inside the above directory, there should be a properties file that has
   information about the cpu or gpu

I'm guessing something is off there, causing rocminfo to crash. As to why
that would be off, I'm not sure except that maybe rocm (KFD or thunk
specifically) didn't get installed right. I could only suggest try
reinstalling it.

Chris

**Comment by jlgreathouse** [comment] 2018-11-19 21:05
Some other useful info would be:
What distro and version is this? What steps did you go through to install ROCm on your system?

If I gave you directions for rebuilding ROCr, ROCt, and rocminfo from source, bug with debug symbols, would you be willing to give us a gdb backtrace?

**Comment by madscientist159** [comment] 2018-11-20 07:00
> Hi, I'm not sure what the issue is. rocminfo just calls the runtime ROCr to get information and display it. ROCr gets the information from sysfs, which is populated by KFD. Usually when there is such a problem it could be that ROCm (the KFD part in particular) isn't running right or isn't installed right. Here are some sysfs files that should have meaningful data: - /sys/devices/virtual/kfd/kfd/topology/nodes/ should have integer number directories, 1 for each gpu or cpu. - inside the above directory, there should be a properties file that has information about the cpu or gpu I'm guessing something is off there, causing rocminfo to crash. As to why that would be off, I'm not sure except that maybe rocm (KFD or thunk specifically) didn't get installed right. I could only suggest try reinstalling it. Chris

```cat properties``` returns nothing.  GPU IDs for the three devices (assuming this is the two NUMA nodes + the GPU) are 0, 0, and 16510.  Since properties isn't returning anything I'm going to focus on that; could be some kind of driver problem.

Would be more than happy to build from source and generate a backtrace.

**Comment by jlgreathouse** [comment] 2018-11-27 06:45
Hi @madscientist159 

Sorry about the delay in getting these directions to you. It's a busy time of the year, and I've been out of the office. The following directions should give you an installation of the Thunk, ROCr, and rocminfo packages that have debug symbols and will hopefully produce a useful backtrace so we can see what's happening.

```bash
# Software needed for this install, on Ubuntu anyway.
sudo apt -y install build-essential cmake pkg-config git libpci-dev libnuma-dev libelf-dev
mkdir -p ~/rocm_src/
mkdir -p ~/rocm_install/

# Download ROCT
cd ~/rocm_src/
git clone -b roc-1.9.x https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface.git
# Build ROCT with debug symbols
cd ./ROCT-Thunk-Interface/
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/rocm_install/
make -j `nproc`
# "Install" ROCT
mkdir -p ~/rocm_install/lib/
mkdir -p ~/rocm_install/include/
make install
cp -R ~/rocm_src/ROCT-Thunk-Interface/include/* ~/rocm_install/include/

# Download ROCr
cd ~/rocm_src/
git clone -b roc-1.9.x https://github.com/RadeonOpenCompute/ROCR-Runtime.git
# Build ROCr with debug symbols
cd ./ROCR-Runtime/src
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/rocm_install/ -DCMAKE_LIBRARY_PATH=~/rocm_install/lib/ -DCMAKE_INCLUDE_PATH=~/rocm_install/include/
make -j `nproc`
# "Install" ROCr
make install
ln -s ~/rocm_install/lib/libhsa-runtime64.so ~/rocm_install/lib/libhsa-runtime64.so.1

# Download rocminfo
cd ~/rocm_src/
git clone https://github.com/RadeonOpenCompute/rocminfo.git
# Build rocminfo with debug symbols
cd rocminfo
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/rocm_install/
make -j `nproc`
# "Install" rocminfo
make install
```

This should put a very minimal ROCm user-land into `~/rocm_install/`. You should be able to run the following command-line to use this custom-built rocminfo with the custom-built ROCr and ROCT.
`LD_LIBRARY_PATH=~/rocm_install/lib/ ~/rocm_install/bin/rocminfo`. You should be able to run this within gdb with `LD_LIBRARY_PATH=~/rocm_install/lib/ gdb ~/rocm_install/bin/rocminfo`

**Comment by jlgreathouse** [comment] 2018-11-27 06:45
In addition, if you could mention what distro you're using and what steps you went through to install ROCm, that may also be helpful. Thanks!

**Comment by madscientist159** [comment] 2018-11-27 08:02
The built version with debug symbols isn't crashing in rocminfo, even when running the rocminfo binary that was installed from the APT source repos.  This is all on Debian Stretch; there are a few reasons why Ubuntu isn't going to work in our environment.

clinfo returns no platforms found; rocminfo shows the card and the CPUs with no problems.  Still investigating the former.

**Comment by jlgreathouse** [comment] 2018-11-27 16:17
Hi @madscientist159 

Thanks for your help with this. Is there any chance you could try this with just the custom-built ROCT? I'd like to try to figure out if this is a ROCR or Thunk issue.

**Comment by madscientist159** [comment] 2018-11-27 21:23
@jlgreathouse Looks like just the custom built ROCT is enough to avoid the crash, so the problem is somewhere in the thunk library.

**Comment by madscientist159** [comment] 2018-11-27 21:48
@jlgreathouse Another data point -- while recompiling and overriding ROCT avoids the crash, OpenCL applications silently fail unless ROCR is also recompiled and overridden.

**Comment by ppanchad-amd** [comment] 2024-08-14 15:01
@madscientist159 Vega is no longer supported on the latest ROCm 6.2. Closing ticket. Thanks!

**Closed by ppanchad-amd** 2024-08-14 15:01 UTC
