### ISSUE TITLE
rocminfo fails when amdgpu is built into the kernel

### ISSUE THREAD

**Issue by FireBurn** [ROCm/rocminfo#42] opened 2021-06-29 16:20 UTC
Is there another way of detecting amdgpu is loaded then running lsmod?

**Comment by fxkamd** [comment] 2021-06-29 16:26
I'm not sure what your question is about. Do you want to find out whether amdgpu loaded successfully? Or are you asking whether rocminfo could use some alternative way to detect amdgpu?

For your own trouble-shooting, check dmesg or "journalctl -k -b".

**Comment by FireBurn** [comment] 2021-06-29 16:34
Sorry I should have been more clear rocminfo doesn't get past https://github.com/RadeonOpenCompute/rocminfo/blob/10da0a71da6700c91e8cd204927cca0d9461b586/rocminfo.cc#L1041

```
rocminfo
ROCk module is NOT loaded, possibly no GPU devices
```

**Comment by skeelyamd** [comment] 2021-06-29 18:56
rocminfo tests for a working kfd and installation very cautiously since many unrelated things can go wrong.  If you've baked amdgpu into your kernel then you could skip the lsmod check since you know you attempted to load the driver.  If for some reason the driver fails to initialize then /dev/kfd will not be present and the next check will detect that.  If you're looking for assistance with your local, custom, build you could simply remove the lsmod check.  On the other hand if you're looking to contribute a rocminfo PR then recording the lsmod failure and continuing on is probably the right direction.  This way rocminfo can print all the possible causes for failure encountered along the way, yet remain quiet if hsa_init actually succeeds despite the failed checks.

**Comment by FireBurn** [comment] 2021-06-29 19:07
I'll think of another way of detecting amdgpu / amdkfd being available

```
diff --git a/rocminfo.cc b/rocminfo.cc
index ee01f60..366982d 100755
--- a/rocminfo.cc
+++ b/rocminfo.cc
@@ -1034,17 +1034,6 @@ AcquireAndDisplayAgentInfo(hsa_agent_t agent, void* data) {
 }
 
 int CheckInitialState(void) {
-  // Check kernel module for ROCk is loaded
-  FILE *fd = popen("lsmod | grep amdgpu", "r");
-  char buf[16];
-  if (fread (buf, 1, sizeof (buf), fd) <= 0) {
-    printf("%sROCk module is NOT loaded, possibly no GPU devices%s\n",
-                                                          COL_RED, COL_RESET);
-    return -1;
-  } else {
-    printf("%sROCk module is loaded%s\n", COL_WHT, COL_RESET);
-  }
-
   // Check if user belongs to the group for /dev/kfd (e.g. "video" or
   // "render")
   // @note: User who are not members of "video"
```

Get's rocminfo working locally for now

**Comment by FireBurn** [comment] 2021-06-29 19:10
Is it enough to check that /sys/module/amdgpu exists?

**Comment by littlewu2508** [comment] 2021-08-18 13:24
> Is it enough to check that /sys/module/amdgpu exists?
I created a PR to implement this: https://github.com/RadeonOpenCompute/rocminfo/pull/43

**Comment by littlewu2508** [comment] 2023-12-19 02:42
> fixed in https://github.com/ROCm/rocminfo/commit/94b4b3f0a66eb70912177ca7076b4267f8b5449b

I think this commit does not fix the issue. The builtin amdgpu kernel module does not have `/sys/module/amdgpu/initstate`. So even after this fix, `rocminfo` still fails with

`ROCk module is NOT loaded, possibly no GPU devices`

**Comment by dmitrii-galantsev** [comment] 2024-01-04 15:56
Hm. I will need to compile the kernel with the driver built-in to test that this approach works.
Will respond in this thread once I make some progress.

Thank you @littlewu2508 for being insistent :)

**Comment by ppanchad-amd** [comment] 2024-08-14 18:02
@dmitrii-galantsev Any update on this issue? Thanks!

**Comment by FireBurn** [comment] 2024-08-14 20:32
So it works on gentoo because it includes this patch https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/rocminfo/files/rocminfo-6.0.0-detect-builtin-amdgpu.patch https://github.com/ROCm/rocminfo/pull/65

**Comment by littlewu2508** [comment] 2024-08-15 06:07
@ppanchad-amd  The issue persists https://github.com/ROCm/rocminfo/pull/43 can be still applied and fix this issue, so I rebased it to amd-staging. Please reopen the PR and have a review.

**Comment by dmitrii-galantsev** [comment] 2024-09-17 20:55
Apologies all. rocminfo fell off my radar. All effort on https://github.com/ROCm/amdsmi...

> So it works on gentoo because it includes this patch https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/rocminfo/files/rocminfo-6.0.0-detect-builtin-amdgpu.patch https://github.com/ROCm/rocminfo/pull/65

@FireBurn Thanks for that, I will try to apply it.

**Comment by dmitrii-galantsev** [comment] 2024-09-19 01:28
@littlewu2508 Hm. I built the kernel with built-in amdgpu. Confirmed that driver is NOT loaded with dkms and manually inserted it with modprobe. I'm still able to observe initstate.

I guess there is no harm in checking for `/sys/module/amdgpu` instead.

**Comment by dmitrii-galantsev** [comment] 2024-09-19 01:49
@littlewu2508 I'm on a modern kernel (6.8.0-1-default+) and was able to rebuild it with amdgpu built in. However it crashed on boot, which is fine.. Even though it crashed, the `/sys/module/amdgpu/` was created, but `/sys/module/amdgpu/initstate` wasn't.

On your system could you please check if amdgpu at all works? Specifically, is there `/sys/class/drm/card*/device/gpu_metrics` ? That would be a good indicator of amdgpu driver working.

**Comment by alexxu-amd** [comment] 2024-10-09 13:54
@littlewu2508 
We have created a PR internally for your code change and it has been merged. Expect the change to come in the future release ;)
Thank you for the contribution!

**Closed by alexxu-amd** 2024-10-09 13:54 UTC
Labels: Under Investigation
